# -*- coding: utf-8 -*-
"""mithun.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1trWpoiIAugYcZ52Z7VpPNrM5UfbnLhDt
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mithun.py
# import streamlit as st
# from PIL import Image
# html_temp = """ 
#   <div style="background-color:pink ;padding:10px">
#   <h2 style="color:white;text-align:center;"> ROOK MATRIMONIAL SERVICES </h2>
#   </div>
#   """ 
# st.markdown(html_temp, unsafe_allow_html=True)
# st.header('மணமகள் கிடைக்கும்')
# m=st.slider('எதிர்பார்த்த வயது',0,100)
# i=st.radio('எதிர்பார்த்த பட்டம்',('B.E','B.Arch','B.Tech','M.Tech','M.E'))
# if st.button('Click to get மணமகள்'):
#   image = Image.open('mithun.jpeg')
#   st.image(image)
#   st.success('உங்களுக்குப் பொருந்தமான மனமகள்')
#   st.header('மிதுலா')